# Generated by Django 4.2.30 on 2026-05-18 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_clubmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', '회장'), ('vice_president', '부회장'), ('executive', '운영진'), ('treasurer', '총무'), ('member', '일반 회원')], default='member', max_length=30)),
                ('status', models.CharField(choices=[('new', '신입 회원'), ('regular', '정회원'), ('inactive', '휴면 회원'), ('withdrawn', '탈퇴 회원'), ('fee_unpaid', '회비 미납자'), ('restricted', '이용 제한 회원')], default='new', max_length=30)),
                ('activity_score', models.IntegerField(default=0)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_memberships', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'club_members_clubmembership',
                'ordering': ['-joined_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clubmembership',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_user_managed_club_membership'),
        ),
    ]
