# Generated by Django 4.2.30 on 2026-06-03 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_surveystate_surveysubmission_surveyitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRelationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('frequent', '자주 함께 활동함'), ('new_member_help', '신입 적응 도움 관계'), ('officer_mentoring', '운영진 멘토링 관계'), ('same_group', '같은 소그룹'), ('need_watch', '관찰 필요'), ('relation_bias', '관계 편중')], max_length=30)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_observations', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relation_observations', to=settings.AUTH_USER_MODEL)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_observations_from', to='club_members.clubmembership')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_observations_to', to='club_members.clubmembership')),
            ],
            options={
                'db_table': 'club_members_relation_observation',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='memberrelationobservation',
            constraint=models.UniqueConstraint(fields=('club', 'from_member', 'to_member', 'tag'), name='unique_relation_observation_per_tag'),
        ),
    ]
