# Generated by Django 4.2.30 on 2026-05-28 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0004_merge_20260519_0655'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='일정명')),
                ('event_type', models.CharField(choices=[('regular', '정기 모임'), ('activity', '행사'), ('recruitment', '모집 일정'), ('interview', '면접 일정'), ('project', '프로젝트 일정'), ('etc', '기타')], default='regular', max_length=30, verbose_name='일정 유형')),
                ('description', models.TextField(blank=True, verbose_name='일정 설명')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='장소')),
                ('start_at', models.DateTimeField(verbose_name='시작 일시')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 일시')),
                ('allow_application', models.BooleanField(default=True, verbose_name='참여 신청 가능 여부')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 참여 인원')),
                ('application_start_at', models.DateTimeField(blank=True, null=True, verbose_name='신청 시작 일시')),
                ('application_end_at', models.DateTimeField(blank=True, null=True, verbose_name='신청 마감 일시')),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('completed', '완료'), ('canceled', '취소')], default='scheduled', max_length=20, verbose_name='일정 상태')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='취소 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정 목록',
                'db_table': 'events_event',
                'ordering': ['-start_at', '-created_at'],
            },
        ),
    ]
