# Generated by Django 4.2.30 on 2026-05-30 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', '신청'), ('canceled', '취소')], default='applied', max_length=20, verbose_name='신청 상태')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='신청 취소 사유')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 일시')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.event', verbose_name='일정')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '일정 참여 신청',
                'verbose_name_plural': '일정 참여 신청 목록',
                'db_table': 'events_event_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', '참석'), ('late', '지각'), ('pre_canceled', '사전 취소'), ('no_show', '무단 불참')], default='present', max_length=20, verbose_name='출석 상태')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='출석 체크 일시')),
                ('memo', models.TextField(blank=True, verbose_name='출석 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='events.eventapplication', verbose_name='참여 신청 정보')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='출석 체크한 운영진')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='일정')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '출석',
                'verbose_name_plural': '출석 목록',
                'db_table': 'events_attendance',
                'ordering': ['event', 'user'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventapplication',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_application_per_user'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_attendance_per_event_user'),
        ),
    ]
