# Generated by Django 4.2.30 on 2026-06-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventapplication_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_score_enabled',
            field=models.BooleanField(default=True, verbose_name='활동 점수 반영 여부'),
        ),
    ]
