# Generated by Django 4.2.30 on 2026-05-18 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출')], max_length=10)),
                ('transaction_date', models.DateField()),
                ('content', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('target', models.CharField(blank=True, max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fee_receipts/', validators=[fees.models.validate_receipt_file])),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='fees.feetransaction')),
            ],
        ),
    ]
