# Generated by Django 4.2.30 on 2026-05-19 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PAID', '완료'), ('UNPAID', '미납')], default='UNPAID', max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='memberfeepayment',
            constraint=models.UniqueConstraint(fields=('club_id', 'user'), name='unique_member_fee_payment_per_club_user'),
        ),
    ]
