# Generated by Django 4.2.30 on 2026-05-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', '관리자'), ('MEMBER', '일반 회원')], default='MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', '활동 중'), ('PENDING', '승인 대기'), ('INACTIVE', '비활동')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='accounts.profile')),
            ],
            options={
                'unique_together': {('club', 'profile')},
            },
        ),
    ]
