# Generated by Django 4.2.30 on 2026-05-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활동 중'), ('PENDING', '승인 대기'), ('INACTIVE', '비활동'), ('REJECTED', '거절됨')], default='ACTIVE', max_length=20),
        ),
    ]
