# Generated by Django 4.2.30 on 2026-05-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubmembership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='max_members',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='club',
            name='recruit_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
