# Generated by Django 4.2.30 on 2026-05-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_clubmembership_status'),
        ('clubs', '0003_rename_max_members_club_capacity_and_more'),
    ]

    operations = [
    ]
