# Generated by Django 4.2.30 on 2026-05-28 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0004_merge_20260519_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiweeklySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('round_number', models.PositiveIntegerField()),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('schedule_items', models.JSONField(blank=True, default=list)),
                ('fee_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_surveys', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_biweekly_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('club', 'year', 'month', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='BiweeklySurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', '임시 저장'), ('SUBMITTED', '최종 제출')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clubs.biweeklysurvey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('survey', 'user')},
            },
        ),
    ]
