# Generated by Django 4.2.30 on 2026-06-01 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0005_biweeklysurvey_biweeklysurveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_version', models.PositiveIntegerField(default=1)),
                ('fee_updated_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_state', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('submitted_version', models.PositiveIntegerField(default=0)),
                ('has_submitted', models.BooleanField(default=False)),
                ('is_resubmitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('draft_updated_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submissions', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('club', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SurveyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('schedule', '일정 만족도'), ('fee', '회비 사용 만족도')], max_length=20)),
                ('original_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('fee_type', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('is_new', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_items', to='clubs.club')),
            ],
            options={
                'ordering': ['-is_new', 'display_order', '-created_at'],
                'unique_together': {('club', 'item_type', 'original_id')},
            },
        ),
    ]
