from django.urls import path

from .views import (
    EventApplicationCancelView,
    EventApplicationListView,
    EventApplyView,
    EventAttendanceCheckView,
    EventAttendanceListView,
    EventDetailView,
    EventListCreateView,
    EventLowParticipationListView,
    EventMemberActivityDetailView,
    EventMemberActivitySummaryView,
    EventNoShowListView,
    EventOperationStatsView,
    EventRecurringCreateView,
    EventReportView,
    EventStatsView,
    EventTimelineView,
    MyEventApplicationView,
    MyEventRoleView,
    MyUpcomingScheduleView,
)


urlpatterns = [
    path(
        "events/my-schedules/",
        MyUpcomingScheduleView.as_view(),
        name="event-my-schedules",
    ),
    path(
        "clubs/<int:club_id>/events/",
        EventListCreateView.as_view(),
        name="event-list-create",
    ),
    path(
        "clubs/<int:club_id>/events/my-role/",
        MyEventRoleView.as_view(),
        name="event-my-role",
    ),
    path(
        "clubs/<int:club_id>/events/member-activity/",
        EventMemberActivitySummaryView.as_view(),
        name="event-member-activity-summary",
    ),
    
    path(
        "clubs/<int:club_id>/events/member-activity/<int:user_id>/",
        EventMemberActivityDetailView.as_view(),
        name="event-member-activity-detail",
    ),
    path(
        "clubs/<int:club_id>/events/low-participation/",
        EventLowParticipationListView.as_view(),
        name="event-low-participation-list",
    ),
    path(
        "clubs/<int:club_id>/events/operation-stats/",
        EventOperationStatsView.as_view(),
        name="event-operation-stats",
    ),
    path(
        "clubs/<int:club_id>/events/recurring/",
        EventRecurringCreateView.as_view(),
        name="event-recurring-create",
    ),
    path(
        "clubs/<int:club_id>/events/timeline/",
        EventTimelineView.as_view(),
        name="event-timeline",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/",
        EventDetailView.as_view(),
        name="event-detail",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/apply/",
        EventApplyView.as_view(),
        name="event-apply",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/cancel-application/",
        EventApplicationCancelView.as_view(),
        name="event-application-cancel",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/my-application/",
        MyEventApplicationView.as_view(),
        name="event-my-application",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/applications/",
        EventApplicationListView.as_view(),
        name="event-application-list",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/attendances/",
        EventAttendanceListView.as_view(),
        name="event-attendance-list",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/attendances/check/",
        EventAttendanceCheckView.as_view(),
        name="event-attendance-check",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/stats/",
        EventStatsView.as_view(),
        name="event-stats",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/no-shows/",
        EventNoShowListView.as_view(),
        name="event-no-show-list",
    ),
    path(
        "clubs/<int:club_id>/events/<int:event_id>/report/",
        EventReportView.as_view(),
        name="event-report",
    ),
]
